= AsciiM3D: Asciidoctor processor for Ribose Standard Documents (M3D)

image:https://img.shields.io/gem/v/metanorma-m3d.svg["Gem Version", link="https://rubygems.org/gems/metanorma-m3d"]
image:https://img.shields.io/travis/riboseinc/metanorma-m3d/master.svg["Build Status", link="https://travis-ci.org/riboseinc/metanorma-m3d"]
image:https://codeclimate.com/github/riboseinc/metanorma-m3d/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/metanorma-m3d"]

WARNING: This gem is still under development.

_Formerly known as_ `asciidoctor-m3d`.

== Functionality

This gem processes http://asciidoctor.org/[Asciidoctor] documents following
a template for generating M3D documents.

The gem currently inherits from the https://github.com/riboseinc/metanorma-standoc
gem, and aligns closely to it. Refer to the ISO gem documentation
for guidance, including https://github.com/riboseinc/metanorma-iso/wiki/Guidance-for-authoring

The following outputs are generated.

* (Optional) An HTML preview generated directly from the Asciidoctor document,
using native Asciidoctor formatting.
** http://asciimath.org[AsciiMathML] is to be used for mathematical formatting.
The gem uses the https://github.com/asciidoctor/asciimath[Ruby AsciiMath parser],
which is syntactically stricter than the common MathJax processor;
if you do not get expected results, try bracketing terms your in AsciiMathML
expressions.
* an XML representation of the document, intended as a document model for M3D
International Standards.
* The XML representation is processed in turn to generate the following outputs
as end deliverable M3D standard drafts.
** HTML
** DOC

This AsciiDoc syntax for writing M3D standards is hereby named "AsciiM3D".

== Usage

The preferred way to invoke this gem is via the `metanorma` script:

[source,console]
----
$ metanorma --type m3d a.adoc                   # output HTML and DOC
$ metanorma --type m3d --extensions html a.adoc # output just HTML
$ metanorma --type m3d --extensions pdf a.adoc  # output just DOC
$ metanorma --type m3d --extensions xml a.adoc  # output M3D XML
----

The gem translates the document into M3D XML format, and then
validates its output against the M3D XML document model; errors are
reported to console against the XML, and are intended for users to
check that they have provided all necessary components of the
document.

The gem then converts the XML into HTML and PDF.

The gem can also be invoked directly within asciidoctor, though this is deprecated:

[source,console]
----
$ asciidoctor -b m3d -r 'metanorma-m3d' a.adoc  
----

=== Installation

If you are using a Mac, the https://github.com/riboseinc/metanorma-macos-setup
repository has instructions on setting up your machine to run Metanorma
scripts such as this one. You need only run the following in a Terminal console:

[source,console]
----
$ bash <(curl -s https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/metanorma-setup)
$ gem install metanorma-m3d
----


== Approach

=== Document model

The Ribose Standard Document model is an instance of the
https://github.com/riboseinc/isodoc-models[StandardDocument model].

The M3D format ("M3D XML") intends to introduce rigor into the M3D
standards authoring process, and is prescribed in a separate document.

M3D XML is still under development, but it already contains all the markup
needed to render a M3D document into HTML.

=== Asciidoctor

Asciidoctor has been selected as the authoring tool to generate the document
model representation of M3D standards. It is a document formatting tool like
Markdown and DocBook, which combines the relative ease of use of the former
(using relatively lightweight markup), and the rigor and expressively of the
latter (it has a well-defined syntax, and was in fact initially developed as a
DocBook document authoring tool). Asciidoctor has built-in capability to output
Text, DocBook and HTML; so it can be used to preview the file as it is being
authored.

Generating documents via a document model substantially automated formatting
associated with the document, including automating numbering of headings, figures,
tables etc, and automatically generating references and citations.

== Document Attributes

=== Common attributes

The gem relies on Asciidoctor document attributes to provide necessary
metadata about the document. The https://github.com/riboseinc/metanorma-standoc[metanorma-standoc]
gem documents the Asciidoctor document attributes common to all metanorma gems. These include:

`:edition:`:: The document edition

`:revdate:`:: The date the document was last updated

`:copyright-year:`:: The year which will be claimed as when the copyright for
the document was issued

`:title:`:: The main component of the English title of the document
(mandatory). (The first line of the AsciiDoc document, which contains the title
introduced with `=`, is ignored)

`:doctype:`:: The document type (see M3D deliverables: The different types of
M3D publications) (mandatory). The permitted types are:
+
--
code:: Code Artifact
presentation:: Presentation
proposal:: Proposal; includes IETF DRAFT
standard:: Recommendation; includes IETF RFC
report:: report
--

`:status:``:: The document status. The permitted types are: `proposal`,
`working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`.

`:technical-committee:`:: The name of the relevant M3D technical committee
(mandatory)

`:language:` :: The language of the document (only `en` for now)  (mandatory)

The attribute `:draft:`, if present, includes review notes in the XML output;
these are otherwise suppressed.

== Asciidoctor features specific to CSAND

The https://github.com/riboseinc/metanorma-standoc[metanorma-standoc]
gem documents the customisations of Asciidoctor markup common to all metanorma gems.
The following markup is specific to this gem:

* `+[keyword]#...#+`: encodes keywords, such as "MUST", "MUST NOT". (Encoded as
`<span class="keyword">...</span>`.

== Data Models

The M3D Standard Document format is an instance of the
https://github.com/riboseinc/isodoc-models[StandardDocument model]. Details of
this general model can be found on its page. Details of the M3D modifications
to this general model can be found on the https://github.com/riboseinc/m3d[M3D model]
repository.

== Examples

* link:spec/examples/rfc6350.adoc[] is an AsciiM3D version of https://tools.ietf.org/html/rfc6350[RFC 6350].
* link:spec/examples/rfc6350.html[] is an HTML file generated from the AsciiM3D.
* link:spec/examples/rfc6350.doc[] is a Word document generated from the AsciiM3D.
